import { useEffect, useLayoutEffect, useRef, useState, type FormEvent } from "react";
import { addDays, formatDate, formatDecimal, parseDecimal, positionInMonthGrid, sortedIndicators, trendDirection, uid, validBackup, type AppData, type Course, type Indicator, type Result } from "./domain";
import { IndexedDbStorage } from "./storage";

type Page = "home" | "more" | "indicators" | "indicator-form" | "history" | "edit-result" | "backup" | "results" | "course" | "edit-course";
const storage = new IndexedDbStorage();
const today = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 10);
export const formatDateInput = (value: string) => { const digits = value.replace(/\D/g, "").slice(0, 8); return [digits.slice(0, 2), digits.slice(2, 4), digits.slice(4, 8)].filter(Boolean).join("."); };
const toRuDate = (iso: string) => { const [year, month, day] = iso.split("-"); return year && month && day ? `${day}.${month}.${year}` : ""; };
export const fromRuDate = (value: string) => { const match = value.trim().match(/^(\d{2})\.(\d{2})\.(\d{4})$/); if (!match) return ""; const [, day, month, year] = match; const iso = `${year}-${month}-${day}`; const date = new Date(`${iso}T00:00:00`); return date.getFullYear() === Number(year) && date.getMonth() + 1 === Number(month) && date.getDate() === Number(day) ? iso : ""; };

export function App() {
  const [data, setData] = useState<AppData>();
  const [page, setPage] = useState<Page>("home");
  const [editing, setEditing] = useState<string>();
  const [notice, setNotice] = useState("");
  useEffect(() => { storage.load().then(setData); }, []);
  const save = (next: AppData, message = "сохранено") => { setData(next); storage.save(next); setNotice(message); window.setTimeout(() => setNotice(""), 2200); };
  const go = (next: Page) => { setPage(next); window.scrollTo(0, 0); };
  if (!data) return <main className="loading">загрузка…</main>;
  const ordered = sortedIndicators(data);
  const formPage = page === "results" || page === "course" || page === "edit-course" || page === "indicator-form" || page === "edit-result";
  const body = page === "home" ? <Home data={data} onResults={() => go("results")} onCourse={() => go("course")} />
    : page === "more" ? <More go={go} />
    : page === "indicators" ? <Indicators data={data} save={save} back={() => go("more")} edit={(id) => { setEditing(id); go("indicator-form"); }} add={() => { setEditing(undefined); go("indicator-form"); }} />
    : page === "indicator-form" ? <IndicatorForm item={data.indicators.find((x) => x.id === editing)} back={() => go("indicators")} save={(item) => { const exists = data.indicators.some((x) => x.id === item.id); save({ ...data, indicators: exists ? data.indicators.map((x) => x.id === item.id ? item : x) : [...data.indicators, item] }, "показатель сохранён"); go("indicators"); }} order={ordered.length} />
    : page === "history" ? <History data={data} save={save} back={() => go("more")} editResult={(id) => { setEditing(id); go("edit-result"); }} editCourse={(id) => { setEditing(id); go("edit-course"); }} />
    : page === "edit-result" ? <EditResult item={data.results.find((x) => x.id === editing)!} data={data} back={() => go("history")} save={(item) => { save({ ...data, results: data.results.map((x) => x.id === item.id ? item : x) }, "результат сохранён"); go("history"); }} remove={() => { save({ ...data, results: data.results.filter((x) => x.id !== editing) }, "результат удалён"); go("history"); }} />
    : page === "results" ? <ResultsForm data={data} back={() => go("home")} save={(items) => { save({ ...data, results: [...data.results, ...items] }, "результаты добавлены"); go("home"); }} />
    : page === "course" ? <CourseForm data={data} back={() => go("home")} save={(course) => { save({ ...data, courses: [...data.courses, course] }, "курс добавлен"); go("home"); }} />
    : page === "edit-course" ? <CourseForm data={data} item={data.courses.find((x) => x.id === editing)} back={() => go("history")} save={(item) => { save({ ...data, courses: data.courses.map((x) => x.id === item.id ? item : x) }, "курс сохранён"); go("history"); }} remove={() => { save({ ...data, courses: data.courses.filter((x) => x.id !== editing) }, "курс удалён"); go("history"); }} />
    : <Backup data={data} save={save} restore={(next) => { save(next, "резервная копия восстановлена"); go("more"); }} back={() => go("more")} />;
  return <div className="app">
    <header><span className="brand">ruby</span></header>
    {notice && <div className="notice">{notice}</div>}
    <main>{body}</main>
    {!formPage && <nav><button className={page === "home" ? "active" : ""} onClick={() => go("home")}>главная</button><button className={page !== "home" ? "active" : ""} onClick={() => go("more")}>ещё</button></nav>}
  </div>;
}

function Home({ data, onResults, onCourse }: { data: AppData; onResults: () => void; onCourse: () => void }) {
  const indicators = sortedIndicators(data).filter((x) => x.showOnHome);
  const allDates = [...data.results.map((x) => x.date), ...data.courses.flatMap((x) => [x.startDate, x.actualEndDate || x.plannedEndDate].filter(Boolean) as string[])];
  const currentYear = new Date().getFullYear(); const years = allDates.map((date) => Number(date.slice(0, 4))); const startYear = Math.min(currentYear, ...years); const endYear = Math.max(currentYear, ...years);
  const timeline = { start: new Date(startYear, 0, 1), end: new Date(endYear, 11, 31), months: Array.from({ length: (endYear - startYear + 1) * 12 }, (_, index) => new Date(startYear, index, 1)) };
  const topDates = indicators[0] ? data.results.filter((x) => x.indicatorId === indicators[0].id).map((x) => x.date).sort() : []; const anchorYear = Number((topDates.at(-1) || `${currentYear}`).slice(0, 4));
  const scrolls = useRef<Array<HTMLDivElement | null>>([]); const syncing = useRef(false);
  useLayoutEffect(() => { const yearOffset = Math.max(0, anchorYear - startYear); scrolls.current.forEach((element) => { if (element) element.scrollLeft = yearOffset * element.clientWidth; }); }, [anchorYear, startYear, indicators.length]);
  const syncScroll = (source: HTMLDivElement) => { if (syncing.current) return; syncing.current = true; const maximum = source.scrollWidth - source.clientWidth; const ratio = maximum > 0 ? source.scrollLeft / maximum : 0; scrolls.current.forEach((element) => { if (element && element !== source) element.scrollLeft = ratio * (element.scrollWidth - element.clientWidth); }); requestAnimationFrame(() => { syncing.current = false; }); };
  return <><section className="intro"><h1>динамика показателей</h1><p>результаты анализов и курсы приёма препаратов в&nbsp;одном месте</p></section><div className="actions"><button className="primary" onClick={onResults}>добавить результаты</button><button className="secondary" onClick={onCourse}>отметить курс</button></div>
    {indicators.map((indicator, index) => <Chart key={indicator.id} indicator={indicator} results={data.results.filter((x) => x.indicatorId === indicator.id)} courses={data.courses.filter((x) => x.indicatorIds.includes(indicator.id))} timeline={timeline} register={(element) => { scrolls.current[index] = element; }} onScroll={syncScroll} />)}
  </>;
}

function Chart({ indicator, results, courses, timeline, register, onScroll }: { indicator: Indicator; results: Result[]; courses: Course[]; timeline: { start: Date; end: Date; months: Date[] }; register: (element: HTMLDivElement | null) => void; onScroll: (element: HTMLDivElement) => void }) {
  const sorted = [...results].sort((a, b) => a.date.localeCompare(b.date));
  const { start, end, months } = timeline; const totalDays = Math.max(1, (end.getTime() - start.getTime()) / 86400000);
  const values = sorted.map((x) => x.value); const min = Math.min(...values, 0); const max = Math.max(...values, 1); const x = (date: string) => 3 + ((new Date(`${date}T00:00:00`).getTime() - start.getTime()) / 86400000 / totalDays) * 94;
  const y = (value: number) => 70 - ((value - min) / Math.max(1, max - min)) * 42;
  const coursePosition = (date: string) => positionInMonthGrid(date, start, months.length);
  return <section className="chart-card"><div className="chart-title"><h2>{indicator.name}</h2><span>{indicator.unit}</span></div>{sorted.length === 0 && courses.length === 0 ? <p className="empty-chart">пока нет данных</p> : <div className="chart-scroll" ref={register} onScroll={(event) => onScroll(event.currentTarget)}><div className="chart" style={{ width: `${Math.max(100, months.length / 12 * 100)}%` }}><div className="plot">
    <svg viewBox="0 0 1000 190" preserveAspectRatio="none" aria-label={`график ${indicator.name}`}>
      {sorted.slice(1).map((item, index) => { const previous = sorted[index]; return <line key={`${previous.id}-${item.id}`} x1={x(previous.date) * 10} y1={y(previous.value) * 1.9} x2={x(item.date) * 10} y2={y(item.value) * 1.9} className={`trend trend-${trendDirection(previous.value, item.value)}`} />; })}
    </svg>{courses.map((course) => { const from = coursePosition(course.startDate); const endDate = course.actualEndDate || course.plannedEndDate; const to = endDate ? coursePosition(endDate) : 100; return <span key={course.id} className="course-band" style={{ left:`${from}%`, width:`${Math.max(4, to - from)}%` }}>курс</span>; })}{sorted.map((item) => <span className="point-marker" key={item.id} style={{ left: `${x(item.date)}%`, top: `${y(item.value)}%` }}><b>{formatDecimal(item.value)}</b><i /></span>)}</div><div className="months">{months.map((month) => { const label = month.toLocaleDateString("ru-RU", { month: "long" }).slice(0, 3); return <span key={month.toISOString()}>{label}{month.getMonth() === 0 && <small>{String(month.getFullYear()).slice(2)}</small>}</span>; })}</div>
  </div></div>}</section>;
}

function DateInput({ value, onChange, required, ariaLabel }: { value: string; onChange: (value: string) => void; required?: boolean; ariaLabel?: string }) { return <div className="date-input"><input inputMode="numeric" placeholder="дд.мм.гггг" aria-label={ariaLabel} required={required} value={value} onChange={(event) => onChange(formatDateInput(event.target.value))} /><span className="date-picker-control"><svg viewBox="0 0 24 24" focusable="false" aria-hidden="true"><path d="M7 3v3m10-3v3M4.5 9h15M6 5h12a2 2 0 0 1 2 2v12H4V7a2 2 0 0 1 2-2Z" /></svg><input className="date-picker-native" type="date" aria-label="выбрать дату в календаре" value={fromRuDate(value)} onChange={(event) => onChange(toRuDate(event.target.value))} /></span></div>; }
function ResultsForm({ data, back, save }: { data: AppData; back: () => void; save: (items: Result[]) => void }) {
  const indicators = sortedIndicators(data); const [date, setDate] = useState(toRuDate(today())); const [rows, setRows] = useState([{ indicatorId: indicators[0]?.id || "", value: "" }]); const [error, setError] = useState("");
  const submit = (e: FormEvent) => { e.preventDefault(); const isoDate = fromRuDate(date); const ids = rows.map((x) => x.indicatorId); const parsed = rows.map((x) => parseDecimal(x.value)); if (!isoDate) return setError("проверьте дату"); if (new Set(ids).size !== ids.length) return setError("один показатель выбран несколько раз"); if (parsed.some((x) => !Number.isFinite(x))) return setError("проверьте значения"); save(rows.map((row, i) => ({ id: uid(), indicatorId: row.indicatorId, date: isoDate, value: parsed[i] }))); };
  return <><ScreenTitle title="добавить результаты" back={back} /><section className="form-card"><form className="form" onSubmit={submit}><Field label="дата"><DateInput ariaLabel="дата" required value={date} onChange={setDate} /></Field>{rows.map((row, index) => <div className="result-row" key={index}><Field label="показатель"><select value={row.indicatorId} onChange={(e) => setRows(rows.map((x, i) => i === index ? { ...x, indicatorId: e.target.value } : x))}>{indicators.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="значение"><input inputMode="decimal" required placeholder="0,0" value={row.value} onChange={(e) => setRows(rows.map((x, i) => i === index ? { ...x, value: e.target.value } : x))} /></Field>{rows.length > 1 && <button type="button" className="remove-row" onClick={() => setRows(rows.filter((_, i) => i !== index))}>удалить показатель</button>}</div>)}<button type="button" className="text-button" onClick={() => setRows([...rows, { indicatorId: indicators.find((x) => !rows.some((r) => r.indicatorId === x.id))?.id || indicators[0]?.id || "", value: "" }])}>+ добавить ещё показатель</button>{error && <p className="error">{error}</p>}<button className="primary">сохранить</button></form></section></>;
}

function CourseForm({ data, item, back, save, remove }: { data: AppData; item?: Course; back: () => void; save: (item: Course) => void; remove?: () => void }) {
  const indicators = sortedIndicators(data); const [indicatorIds, setIndicatorIds] = useState(item?.indicatorIds || [indicators[0]?.id || ""]); const [startDate, setStartDate] = useState(toRuDate(item?.startDate || today())); const [plannedEndDate, setPlanned] = useState(toRuDate(item?.plannedEndDate || "")); const [actualEndDate, setActual] = useState(toRuDate(item?.actualEndDate || "")); const [days, setDays] = useState(item?.days?.toString() || ""); const [error, setError] = useState(""); const [confirmingDelete, setConfirmingDelete] = useState(false);
  const submit = (e: FormEvent) => { e.preventDefault(); const startIso = fromRuDate(startDate); const plannedIso = plannedEndDate ? fromRuDate(plannedEndDate) : ""; const actualIso = actualEndDate ? fromRuDate(actualEndDate) : ""; if (indicatorIds.length === 0) return setError("выберите хотя бы один показатель"); if (!startIso || (plannedEndDate && !plannedIso) || (actualEndDate && !actualIso)) return setError("проверьте даты"); const count = Number(days); save({ id: item?.id || uid(), indicatorIds, startDate: startIso, plannedEndDate: plannedIso || (count > 0 ? addDays(startIso, count) : undefined), actualEndDate: actualIso || undefined, days: count > 0 ? count : undefined }); };
  const selectedNames = indicators.filter((indicator) => indicatorIds.includes(indicator.id)).map((indicator) => indicator.name).join(", ");
  return <><ScreenTitle title={item ? "изменить курс" : "отметить курс"} back={back} /><section className="form-card"><form className="form" onSubmit={submit}><Field label="показатели"><details className="multi-select"><summary>{selectedNames || "выберите показатели"}</summary><div>{indicators.map((indicator) => <label key={indicator.id}><input type="checkbox" checked={indicatorIds.includes(indicator.id)} onChange={(event) => setIndicatorIds(event.target.checked ? [...indicatorIds, indicator.id] : indicatorIds.filter((id) => id !== indicator.id))} /><span>{indicator.name}</span></label>)}</div></details></Field><Field label="дата начала"><DateInput ariaLabel="дата начала" required value={startDate} onChange={setStartDate} /></Field><Field label="дата окончания" optional><DateInput ariaLabel="дата окончания" value={plannedEndDate} onChange={(value) => { setPlanned(value); if (value) setDays(""); }} /></Field><Field label="количество дней" optional><input inputMode="numeric" type="number" min="1" placeholder="90" value={days} onChange={(e) => { setDays(e.target.value); if (e.target.value) setPlanned(""); }} /></Field>{item && <Field label="фактическая дата окончания" optional><DateInput ariaLabel="фактическая дата окончания" value={actualEndDate} onChange={setActual} /></Field>}{error && <p className="error">{error}</p>}<button className="primary">сохранить</button>{remove && <button type="button" className="danger-link" onClick={() => setConfirmingDelete(true)}>удалить курс</button>}</form></section>{confirmingDelete && remove && <ConfirmDialog title="удалить курс?" cancel={() => setConfirmingDelete(false)} confirm={remove} />}</>;
}

function More({ go }: { go: (page: Page) => void }) { return <section className="menu"><button onClick={() => go("indicators")}><span>показатели</span><b>›</b></button><button onClick={() => go("history")}><span>история</span><b>›</b></button><button onClick={() => go("backup")}><span>резервная копия</span><b>›</b></button></section>; }
function ScreenTitle({ title, back }: { title: string; back: () => void }) { return <div className="screen-title"><button className="back" aria-label="назад" onClick={back}>‹</button><h1>{title}</h1></div>; }
function ConfirmDialog({ title, cancel, confirm, confirmLabel = "удалить" }: { title: string; cancel: () => void; confirm: () => void; confirmLabel?: string }) { return <div className="confirm-overlay" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && cancel()}><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{title}</h2><div><button className="secondary" onClick={cancel}>отмена</button><button className="primary" onClick={confirm}>{confirmLabel}</button></div></section></div>; }
function Indicators({ data, save, back, edit, add }: { data: AppData; save: (d: AppData, m?: string) => void; back: () => void; edit: (id: string) => void; add: () => void }) {
  const items = sortedIndicators(data); const [dragged, setDragged] = useState<string>(); const [pendingDelete, setPendingDelete] = useState<Indicator>(); const persist = (next: Indicator[]) => save({ ...data, indicators: next.map((x, order) => ({ ...x, order })) }, "порядок сохранён"); const move = (index: number, direction: number) => { const target = index + direction; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target], items[index]]; persist(items); }; const drop = (targetId: string) => { if (!dragged || dragged === targetId) return; const next = [...items]; const from = next.findIndex((x) => x.id === dragged); const to = next.findIndex((x) => x.id === targetId); const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setDragged(undefined); persist(next); };
  const remove = (item: Indicator) => save({ ...data, indicators: data.indicators.filter((x) => x.id !== item.id), results: data.results.filter((x) => x.indicatorId !== item.id), courses: data.courses.map((course) => ({ ...course, indicatorIds: course.indicatorIds.filter((id) => id !== item.id) })).filter((course) => course.indicatorIds.length > 0) }, "показатель удалён");
  return <><ScreenTitle title="показатели" back={back} /><section className="card">{items.map((item, index) => <div className="indicator-row" key={item.id} draggable onDragStart={() => setDragged(item.id)} onDragOver={(e) => e.preventDefault()} onDrop={() => drop(item.id)}><button className="drag-handle" aria-label="перетащить" onClick={() => move(index, index === items.length - 1 ? -1 : 1)}>☰</button><span><b>{item.name}</b><small>{item.unit}</small></span><span className="row-actions"><button className="pencil" onClick={() => edit(item.id)} aria-label={`изменить ${item.name}`}>✎</button><button className="delete" onClick={() => setPendingDelete(item)} aria-label={`удалить ${item.name}`}>×</button></span></div>)}</section><button className="secondary" onClick={add}>добавить показатель</button>{pendingDelete && <ConfirmDialog title="удалить показатель?" cancel={() => setPendingDelete(undefined)} confirm={() => { remove(pendingDelete); setPendingDelete(undefined); }} />}</>;
}
function IndicatorForm({ item, back, save, order }: { item?: Indicator; back: () => void; save: (x: Indicator) => void; order: number }) { const [name, setName] = useState(item?.name || ""); const [unit, setUnit] = useState(item?.unit || ""); return <><ScreenTitle title={item ? "изменить показатель" : "добавить показатель"} back={back} /><section className="form-card"><form onSubmit={(e) => { e.preventDefault(); save({ id: item?.id || uid(), name: name.trim(), unit: unit.trim(), order: item?.order ?? order, showOnHome: item?.showOnHome ?? true }); }}><Field label="название"><input required value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="единица измерения"><input required value={unit} onChange={(e) => setUnit(e.target.value)} /></Field><button className="primary">сохранить</button></form></section></>; }

function History({ data, save, back, editResult, editCourse }: { data: AppData; save: (d: AppData, m?: string) => void; back: () => void; editResult: (id: string) => void; editCourse: (id: string) => void }) { const [pendingDelete, setPendingDelete] = useState<{ kind: "результат" | "курс"; id: string }>(); const confirmRemove = () => { if (!pendingDelete) return; if (pendingDelete.kind === "результат") save({ ...data, results: data.results.filter((x) => x.id !== pendingDelete.id) }, "результат удалён"); else save({ ...data, courses: data.courses.filter((x) => x.id !== pendingDelete.id) }, "курс удалён"); setPendingDelete(undefined); }; const actions = (edit: () => void, remove: () => void) => <span className="row-actions"><button className="pencil" onClick={edit}>✎</button><button className="delete" onClick={remove}>×</button></span>; return <><ScreenTitle title="история" back={back} />{sortedIndicators(data).map((indicator) => { const results = data.results.filter((x) => x.indicatorId === indicator.id).sort((a, b) => b.date.localeCompare(a.date)); const courses = data.courses.filter((x) => x.indicatorIds.includes(indicator.id)).sort((a, b) => b.startDate.localeCompare(a.startDate)); return <section className="history-card card" key={indicator.id}><div className="chart-title"><h2>{indicator.name}</h2><span>{indicator.unit}</span></div>{results.length === 0 && courses.length === 0 && <p className="muted">пока нет данных</p>}{results.map((x) => <div className="history-row" key={x.id}><span>{formatDate(x.date)}</span><em>{formatDecimal(x.value)}</em>{actions(() => editResult(x.id), () => setPendingDelete({ kind: "результат", id: x.id }))}</div>)}{courses.length > 0 && <h3>курсы</h3>}{courses.map((x) => <div className="history-row course-row" key={x.id}><span>{formatDate(x.startDate)} — {x.actualEndDate ? formatDate(x.actualEndDate) : x.plannedEndDate ? formatDate(x.plannedEndDate) : "идёт"}</span>{actions(() => editCourse(x.id), () => setPendingDelete({ kind: "курс", id: x.id }))}</div>)}</section>; })}{pendingDelete && <ConfirmDialog title={`удалить ${pendingDelete.kind}?`} cancel={() => setPendingDelete(undefined)} confirm={confirmRemove} />}</>; }
function EditResult({ item, data, back, save, remove }: { item: Result; data: AppData; back: () => void; save: (x: Result) => void; remove: () => void }) { const [date, setDate] = useState(toRuDate(item.date)); const [value, setValue] = useState(formatDecimal(item.value)); const [indicatorId, setIndicator] = useState(item.indicatorId); const [confirmingDelete, setConfirmingDelete] = useState(false); return <><ScreenTitle title="изменить результат" back={back} /><section className="form-card"><form className="form" onSubmit={(e) => { e.preventDefault(); const number = parseDecimal(value); const isoDate = fromRuDate(date); if (Number.isFinite(number) && isoDate) save({ ...item, date: isoDate, value: number, indicatorId }); }}><Field label="дата"><DateInput ariaLabel="дата" value={date} onChange={setDate} /></Field><Field label="показатель"><select value={indicatorId} onChange={(e) => setIndicator(e.target.value)}>{sortedIndicators(data).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="значение"><input inputMode="decimal" value={value} onChange={(e) => setValue(e.target.value)} /></Field><button className="primary">сохранить</button><button type="button" className="danger-link" onClick={() => setConfirmingDelete(true)}>удалить результат</button></form></section>{confirmingDelete && <ConfirmDialog title="удалить результат?" cancel={() => setConfirmingDelete(false)} confirm={remove} />}</>; }
function Backup({ data, save, restore, back }: { data: AppData; save: (d: AppData, m?: string) => void; restore: (d: AppData) => void; back: () => void }) { const input = useRef<HTMLInputElement>(null); const [pendingRestore, setPendingRestore] = useState<AppData>(); const download = () => { const stamp = today(); const next = { ...data, lastBackupDate: stamp }; const blob = new Blob([JSON.stringify(next, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `ruby-backup-${stamp}.json`; link.click(); URL.revokeObjectURL(link.href); save(next, "резервная копия создана"); }; const upload = async (file?: File) => { if (!file) return; try { const value = JSON.parse(await file.text()); if (!validBackup(value)) throw new Error(); setPendingRestore(value); } catch { alert("не удалось прочитать резервную копию"); } }; return <><ScreenTitle title="резервная копия" back={back} /><section className="card backup"><p>{data.lastBackupDate ? `последняя резервная копия: ${formatDate(data.lastBackupDate)}` : "резервная копия ещё не создавалась"}</p><button className="primary" onClick={download}>создать резервную копию</button><button className="secondary" onClick={() => input.current?.click()}>восстановить резервную копию</button><input ref={input} hidden type="file" accept="application/json" onChange={(e) => upload(e.target.files?.[0])} /></section>{pendingRestore && <ConfirmDialog title="восстановить резервную копию?" confirmLabel="восстановить" cancel={() => setPendingRestore(undefined)} confirm={() => restore(pendingRestore)} />}</>; }
function Field({ label, optional, children }: { label: string; optional?: boolean; children: React.ReactNode }) { return <label className="field"><span>{label}{optional && <> <small>(необязательно)</small></>}</span>{children}</label>; }
