import { useEffect, useRef, useState, type FormEvent } from "react";
import { addDays, formatDate, formatDecimal, parseDecimal, sortedIndicators, uid, validBackup, type AppData, type Course, type Indicator, type Result } from "./domain";
import { IndexedDbStorage } from "./storage";

type Page = "home" | "more" | "indicators" | "history" | "backup";
type Modal = "results" | "course" | "indicator" | "edit-result" | "edit-course" | null;
const storage = new IndexedDbStorage();
const today = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 10);

export function App() {
  const [data, setData] = useState<AppData>();
  const [page, setPage] = useState<Page>("home");
  const [modal, setModal] = useState<Modal>(null);
  const [editing, setEditing] = useState<string>();
  const [notice, setNotice] = useState("");
  useEffect(() => { storage.load().then(setData); }, []);
  const save = (next: AppData, message = "сохранено") => { setData(next); storage.save(next); setNotice(message); window.setTimeout(() => setNotice(""), 2200); };
  const open = (next: Modal, id?: string) => { setEditing(id); setModal(next); };
  const go = (next: Page) => { setPage(next); window.scrollTo(0, 0); };
  if (!data) return <main className="loading">загрузка…</main>;
  const ordered = sortedIndicators(data);
  const body = page === "home" ? <Home data={data} onResults={() => open("results")} onCourse={() => open("course")} />
    : page === "more" ? <More go={go} />
    : page === "indicators" ? <Indicators data={data} save={save} back={() => go("more")} edit={(id) => open("indicator", id)} add={() => open("indicator")} />
    : page === "history" ? <History data={data} save={save} back={() => go("more")} editResult={(id) => open("edit-result", id)} editCourse={(id) => open("edit-course", id)} />
    : <Backup data={data} save={save} restore={(next) => { save(next, "резервная копия восстановлена"); go("more"); }} back={() => go("more")} />;
  return <div className="app">
    {notice && <div className="notice">{notice}</div>}
    <main>{body}</main>
    <nav><button className={page === "home" ? "active" : ""} onClick={() => go("home")}>главная</button><button className={page !== "home" ? "active" : ""} onClick={() => go("more")}>ещё</button></nav>
    {modal === "results" && <ResultsForm data={data} close={() => setModal(null)} save={(items) => { save({ ...data, results: [...data.results, ...items] }, "результаты добавлены"); setModal(null); }} />}
    {modal === "course" && <CourseForm data={data} close={() => setModal(null)} save={(course) => { save({ ...data, courses: [...data.courses, course] }, "курс добавлен"); setModal(null); }} />}
    {modal === "indicator" && <IndicatorForm item={data.indicators.find((x) => x.id === editing)} close={() => setModal(null)} save={(item) => { const exists = data.indicators.some((x) => x.id === item.id); save({ ...data, indicators: exists ? data.indicators.map((x) => x.id === item.id ? item : x) : [...data.indicators, item] }, "показатель сохранён"); setModal(null); }} order={ordered.length} />}
    {modal === "edit-result" && <EditResult item={data.results.find((x) => x.id === editing)!} data={data} close={() => setModal(null)} save={(item) => { save({ ...data, results: data.results.map((x) => x.id === item.id ? item : x) }, "результат сохранён"); setModal(null); }} remove={() => { save({ ...data, results: data.results.filter((x) => x.id !== editing) }, "результат удалён"); setModal(null); }} />}
    {modal === "edit-course" && <CourseForm data={data} item={data.courses.find((x) => x.id === editing)} close={() => setModal(null)} save={(item) => { save({ ...data, courses: data.courses.map((x) => x.id === item.id ? item : x) }, "курс сохранён"); setModal(null); }} remove={() => { save({ ...data, courses: data.courses.filter((x) => x.id !== editing) }, "курс удалён"); setModal(null); }} />}
  </div>;
}

function Home({ data, onResults, onCourse }: { data: AppData; onResults: () => void; onCourse: () => void }) {
  const indicators = sortedIndicators(data).filter((x) => x.showOnHome);
  return <><section className="intro"><h1>динамика показателей</h1><p>результаты анализов и курсы приёма препаратов в одном месте</p></section><div className="actions"><button className="primary" onClick={onResults}>добавить результаты</button><button className="secondary" onClick={onCourse}>отметить курс</button></div>
    {indicators.map((indicator) => <Chart key={indicator.id} indicator={indicator} results={data.results.filter((x) => x.indicatorId === indicator.id)} courses={data.courses.filter((x) => x.indicatorId === indicator.id)} />)}
  </>;
}

function Chart({ indicator, results, courses }: { indicator: Indicator; results: Result[]; courses: Course[] }) {
  const sorted = [...results].sort((a, b) => a.date.localeCompare(b.date));
  const allDates = [...sorted.map((x) => x.date), ...courses.flatMap((x) => [x.startDate, x.actualEndDate || x.plannedEndDate].filter(Boolean) as string[])];
  const now = new Date(); const first = allDates.length ? new Date(`${[...allDates].sort()[0]}T00:00:00`) : now;
  const start = new Date(first.getFullYear(), first.getMonth(), 1); const end = new Date(Math.max(now.getFullYear(), first.getFullYear()), Math.max(now.getFullYear() === first.getFullYear() ? now.getMonth() : 11, first.getMonth()) + 1, 0);
  while ((end.getFullYear() - start.getFullYear()) * 12 + end.getMonth() - start.getMonth() < 11) end.setMonth(end.getMonth() + 1);
  const totalDays = Math.max(1, (end.getTime() - start.getTime()) / 86400000); const months = Array.from({ length: (end.getFullYear() - start.getFullYear()) * 12 + end.getMonth() - start.getMonth() + 1 }, (_, i) => new Date(start.getFullYear(), start.getMonth() + i, 1));
  const values = sorted.map((x) => x.value); const min = Math.min(...values, 0); const max = Math.max(...values, 1); const x = (date: string) => 3 + ((new Date(`${date}T00:00:00`).getTime() - start.getTime()) / 86400000 / totalDays) * 94;
  const y = (value: number) => 70 - ((value - min) / Math.max(1, max - min)) * 42;
  return <section className="chart-card"><div className="chart-title"><h2>{indicator.name}</h2><span>{indicator.unit}</span></div>{sorted.length === 0 && courses.length === 0 ? <p className="empty-chart">пока нет данных</p> : <div className="chart-scroll"><div className="chart" style={{ width: `${Math.max(100, months.length / 12 * 100)}%` }}>
    <svg viewBox="0 0 1000 190" preserveAspectRatio="none" aria-label={`график ${indicator.name}`}>
      {sorted.length > 1 && <polyline points={sorted.map((item) => `${x(item.date) * 10},${y(item.value) * 1.9}`).join(" ")} className="trend" />}
      {courses.map((course) => { const from = x(course.startDate) * 10; const endDate = course.actualEndDate || course.plannedEndDate; const to = endDate ? x(endDate) * 10 : 1000; return <g key={course.id} className="course-mark"><line x1={from} y1="35" x2={from} y2="142"/><line x1={from} y1="35" x2={to} y2="35"/><text x={(from + to) / 2} y="25">курс</text>{endDate && <line x1={to} y1="35" x2={to} y2="142"/>}</g>; })}
    </svg>{sorted.map((item) => <span className="point-marker" key={item.id} style={{ left: `${x(item.date)}%`, top: `${y(item.value)}%` }}><b>{formatDecimal(item.value)}</b><i /></span>)}<div className="months">{months.map((month) => { const label = month.toLocaleDateString("ru-RU", { month: "long" }).slice(0, 3); return <span key={month.toISOString()}>{label}{month.getMonth() === 0 && <small>{String(month.getFullYear()).slice(2)}</small>}</span>; })}</div>
  </div></div>}</section>;
}

function Sheet({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="overlay" onMouseDown={(e) => e.target === e.currentTarget && close()}><section className="sheet"><div className="sheet-head"><h1>{title}</h1><button className="icon" onClick={close} aria-label="закрыть">×</button></div>{children}</section></div>; }
function ResultsForm({ data, close, save }: { data: AppData; close: () => void; save: (items: Result[]) => void }) {
  const indicators = sortedIndicators(data); const [date, setDate] = useState(today()); const [rows, setRows] = useState([{ indicatorId: indicators[0]?.id || "", value: "" }]); const [error, setError] = useState("");
  const submit = (e: FormEvent) => { e.preventDefault(); const ids = rows.map((x) => x.indicatorId); const parsed = rows.map((x) => parseDecimal(x.value)); if (new Set(ids).size !== ids.length) return setError("один показатель выбран несколько раз"); if (parsed.some((x) => !Number.isFinite(x))) return setError("проверьте значения"); save(rows.map((row, i) => ({ id: uid(), indicatorId: row.indicatorId, date, value: parsed[i] }))); };
  return <Sheet title="добавить результаты" close={close}><form onSubmit={submit}><Field label="дата"><input type="date" required value={date} onChange={(e) => setDate(e.target.value)} /></Field>{rows.map((row, index) => <div className="result-row" key={index}><Field label="показатель"><select value={row.indicatorId} onChange={(e) => setRows(rows.map((x, i) => i === index ? { ...x, indicatorId: e.target.value } : x))}>{indicators.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="значение"><input inputMode="decimal" required placeholder="0,0" value={row.value} onChange={(e) => setRows(rows.map((x, i) => i === index ? { ...x, value: e.target.value } : x))} /></Field>{rows.length > 1 && <button type="button" className="remove-row" onClick={() => setRows(rows.filter((_, i) => i !== index))} aria-label="удалить строку">×</button>}</div>)}<button type="button" className="text-button" onClick={() => setRows([...rows, { indicatorId: indicators.find((x) => !rows.some((r) => r.indicatorId === x.id))?.id || indicators[0]?.id || "", value: "" }])}>+ добавить ещё показатель</button>{error && <p className="error">{error}</p>}<button className="primary">сохранить</button></form></Sheet>;
}

function CourseForm({ data, item, close, save, remove }: { data: AppData; item?: Course; close: () => void; save: (item: Course) => void; remove?: () => void }) {
  const indicators = sortedIndicators(data); const [indicatorId, setIndicatorId] = useState(item?.indicatorId || indicators[0]?.id || ""); const [startDate, setStartDate] = useState(item?.startDate || today()); const [plannedEndDate, setPlanned] = useState(item?.plannedEndDate || ""); const [actualEndDate, setActual] = useState(item?.actualEndDate || ""); const [days, setDays] = useState(item?.days?.toString() || "");
  const submit = (e: FormEvent) => { e.preventDefault(); const count = Number(days); save({ id: item?.id || uid(), indicatorId, startDate, plannedEndDate: plannedEndDate || (count > 0 ? addDays(startDate, count) : undefined), actualEndDate: actualEndDate || undefined, days: count > 0 ? count : undefined }); };
  return <Sheet title={item ? "изменить курс" : "отметить курс"} close={close}><form onSubmit={submit}><Field label="показатель"><select value={indicatorId} onChange={(e) => setIndicatorId(e.target.value)}>{indicators.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="дата начала"><input type="date" required value={startDate} onChange={(e) => setStartDate(e.target.value)} /></Field><Field label="дата окончания" optional><input type="date" value={plannedEndDate} onChange={(e) => { setPlanned(e.target.value); if (e.target.value) setDays(""); }} /></Field><div className="or">или</div><Field label="количество дней" optional><input inputMode="numeric" type="number" min="1" placeholder="90" value={days} onChange={(e) => { setDays(e.target.value); if (e.target.value) setPlanned(""); }} /></Field>{item && <Field label="фактическая дата окончания" optional><input type="date" value={actualEndDate} onChange={(e) => setActual(e.target.value)} /></Field>}<button className="primary">сохранить</button>{remove && <button type="button" className="danger-link" onClick={() => confirm("удалить курс?") && remove()}>удалить курс</button>}</form></Sheet>;
}

function More({ go }: { go: (page: Page) => void }) { return <section className="menu"><button onClick={() => go("indicators")}><span>показатели</span><b>›</b></button><button onClick={() => go("history")}><span>история</span><b>›</b></button><button onClick={() => go("backup")}><span>резервная копия</span><b>›</b></button></section>; }
function ScreenTitle({ title, back }: { title: string; back: () => void }) { return <div className="screen-title"><button className="back" onClick={back}>‹</button><h1>{title}</h1></div>; }
function Indicators({ data, save, back, edit, add }: { data: AppData; save: (d: AppData, m?: string) => void; back: () => void; edit: (id: string) => void; add: () => void }) {
  const items = sortedIndicators(data); const [dragged, setDragged] = useState<string>(); const persist = (next: Indicator[]) => save({ ...data, indicators: next.map((x, order) => ({ ...x, order })) }, "порядок сохранён"); const move = (index: number, direction: number) => { const target = index + direction; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target], items[index]]; persist(items); }; const drop = (targetId: string) => { if (!dragged || dragged === targetId) return; const next = [...items]; const from = next.findIndex((x) => x.id === dragged); const to = next.findIndex((x) => x.id === targetId); const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setDragged(undefined); persist(next); };
  const remove = (item: Indicator) => { if (!confirm(`удалить показатель «${item.name}» и все его данные?`)) return; save({ ...data, indicators: data.indicators.filter((x) => x.id !== item.id), results: data.results.filter((x) => x.indicatorId !== item.id), courses: data.courses.filter((x) => x.indicatorId !== item.id) }, "показатель удалён"); };
  return <><ScreenTitle title="показатели" back={back} /><section className="card">{items.map((item, index) => <div className="indicator-row" key={item.id} draggable onDragStart={() => setDragged(item.id)} onDragOver={(e) => e.preventDefault()} onDrop={() => drop(item.id)}><button className="drag-handle" aria-label="перетащить" onClick={() => move(index, index === items.length - 1 ? -1 : 1)}>☰</button><span><b>{item.name}</b><small>{item.unit}</small></span><button className="pencil" onClick={() => edit(item.id)} aria-label={`изменить ${item.name}`}>✎</button><button className="delete" onClick={() => remove(item)} aria-label={`удалить ${item.name}`}>×</button></div>)}</section><button className="secondary" onClick={add}>добавить показатель</button></>;
}
function IndicatorForm({ item, close, save, order }: { item?: Indicator; close: () => void; save: (x: Indicator) => void; order: number }) { const [name, setName] = useState(item?.name || ""); const [unit, setUnit] = useState(item?.unit || ""); return <Sheet title={item ? "изменить показатель" : "добавить показатель"} close={close}><form onSubmit={(e) => { e.preventDefault(); save({ id: item?.id || uid(), name: name.trim(), unit: unit.trim(), order: item?.order ?? order, showOnHome: item?.showOnHome ?? true }); }}><Field label="название"><input required value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="единица измерения"><input required value={unit} onChange={(e) => setUnit(e.target.value)} /></Field><button className="primary">сохранить</button></form></Sheet>; }

function History({ data, save, back, editResult, editCourse }: { data: AppData; save: (d: AppData, m?: string) => void; back: () => void; editResult: (id: string) => void; editCourse: (id: string) => void }) { const removeResult = (id: string) => confirm("удалить результат?") && save({ ...data, results: data.results.filter((x) => x.id !== id) }, "результат удалён"); const removeCourse = (id: string) => confirm("удалить курс?") && save({ ...data, courses: data.courses.filter((x) => x.id !== id) }, "курс удалён"); return <><ScreenTitle title="история" back={back} />{sortedIndicators(data).map((indicator) => { const results = data.results.filter((x) => x.indicatorId === indicator.id).sort((a, b) => b.date.localeCompare(a.date)); const courses = data.courses.filter((x) => x.indicatorId === indicator.id).sort((a, b) => b.startDate.localeCompare(a.startDate)); return <section className="history-card card" key={indicator.id}><div className="chart-title"><h2>{indicator.name}</h2><span>{indicator.unit}</span></div>{results.length === 0 && courses.length === 0 && <p className="muted">пока нет данных</p>}{results.map((x) => <div className="history-row" key={x.id}><span>{formatDate(x.date)}</span><em>{formatDecimal(x.value)}</em><button className="pencil" onClick={() => editResult(x.id)}>✎</button><button className="delete" onClick={() => removeResult(x.id)}>×</button></div>)}{courses.length > 0 && <h3>курсы</h3>}{courses.map((x) => <div className="history-row course-row" key={x.id}><span>{formatDate(x.startDate)} — {x.actualEndDate ? formatDate(x.actualEndDate) : x.plannedEndDate ? `${formatDate(x.plannedEndDate)} (план)` : "идёт"}</span><button className="pencil" onClick={() => editCourse(x.id)}>✎</button><button className="delete" onClick={() => removeCourse(x.id)}>×</button></div>)}</section>; })}</>; }
function EditResult({ item, data, close, save, remove }: { item: Result; data: AppData; close: () => void; save: (x: Result) => void; remove: () => void }) { const [date, setDate] = useState(item.date); const [value, setValue] = useState(formatDecimal(item.value)); const [indicatorId, setIndicator] = useState(item.indicatorId); return <Sheet title="изменить результат" close={close}><form onSubmit={(e) => { e.preventDefault(); const number = parseDecimal(value); if (Number.isFinite(number)) save({ ...item, date, value: number, indicatorId }); }}><Field label="дата"><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><Field label="показатель"><select value={indicatorId} onChange={(e) => setIndicator(e.target.value)}>{sortedIndicators(data).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="значение"><input inputMode="decimal" value={value} onChange={(e) => setValue(e.target.value)} /></Field><button className="primary">сохранить</button><button type="button" className="danger-link" onClick={() => confirm("удалить результат?") && remove()}>удалить результат</button></form></Sheet>; }
function Backup({ data, save, restore, back }: { data: AppData; save: (d: AppData, m?: string) => void; restore: (d: AppData) => void; back: () => void }) { const input = useRef<HTMLInputElement>(null); const download = () => { const stamp = today(); const next = { ...data, lastBackupDate: stamp }; const blob = new Blob([JSON.stringify(next, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `ruby-backup-${stamp}.json`; link.click(); URL.revokeObjectURL(link.href); save(next, "резервная копия создана"); }; const upload = async (file?: File) => { if (!file) return; try { const value = JSON.parse(await file.text()); if (!validBackup(value)) throw new Error(); if (confirm("заменить текущие данные резервной копией?")) restore(value); } catch { alert("не удалось прочитать резервную копию"); } }; return <><ScreenTitle title="резервная копия" back={back} /><section className="card backup"><p>{data.lastBackupDate ? `последняя резервная копия: ${formatDate(data.lastBackupDate)}` : "резервная копия ещё не создавалась"}</p><button className="primary" onClick={download}>создать резервную копию</button><button className="secondary" onClick={() => input.current?.click()}>восстановить резервную копию</button><input ref={input} hidden type="file" accept="application/json" onChange={(e) => upload(e.target.files?.[0])} /></section></>; }
function Field({ label, optional, children }: { label: string; optional?: boolean; children: React.ReactNode }) { return <label className="field"><span>{label} {optional && <small>(не обязательно)</small>}</span>{children}</label>; }
